title: Services
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          localizable: true
          validate:
            - required
      -
        handle: header_image
        field:
          mode: grid
          container: assets
          restrict: false
          allow_uploads: true
          max_files: 1
          display: 'Header Image'
          type: assets
          icon: assets
          listable: hidden
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
          required: true
          validate:
            - required
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
      -
        handle: template
        field:
          hide_partials: true
          display: Template
          type: template
          icon: template
          listable: hidden
  services:
    display: Services
    fields:
      -
        handle: title1
        field:
          input_type: text
          antlers: false
          display: 'Section 1 Title'
          type: text
          icon: text
          localizable: true
          listable: hidden
      -
        handle: short_title1
        field:
          input_type: text
          antlers: false
          display: 'Section 1 Short Title'
          type: text
          icon: text
          localizable: true
          listable: hidden
      -
        handle: content1
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: false
          display: 'Section 1 Content'
          type: markdown
          icon: markdown
          localizable: true
          listable: hidden
      -
        handle: title2
        field:
          input_type: text
          antlers: false
          display: 'Section 2 Title'
          type: text
          icon: text
          localizable: true
          listable: hidden
      -
        handle: short_title2
        field:
          input_type: text
          antlers: false
          display: 'Section 2 Short Title'
          type: text
          icon: text
          localizable: true
          listable: hidden
      -
        handle: content2
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: false
          display: 'Section 2 Content'
          type: markdown
          icon: markdown
          localizable: true
          listable: hidden
      -
        handle: image2
        field:
          mode: grid
          container: assets
          restrict: false
          allow_uploads: true
          max_files: 1
          display: 'Section 2 Image'
          type: assets
          icon: assets
          listable: hidden
      -
        handle: title3
        field:
          input_type: text
          antlers: false
          display: 'Section 3 Title'
          type: text
          icon: text
          localizable: true
          listable: hidden
      -
        handle: short_title3
        field:
          input_type: text
          antlers: false
          display: 'Section 3 Short Title'
          type: text
          icon: text
          localizable: true
          listable: hidden
      -
        handle: content3
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: false
          display: 'Section 3 Content'
          type: markdown
          icon: markdown
          localizable: true
          listable: hidden
      -
        handle: image3
        field:
          mode: grid
          container: assets
          restrict: false
          allow_uploads: true
          max_files: 1
          display: 'Section 3 Image'
          type: assets
          icon: assets
          listable: hidden
      -
        handle: title4
        field:
          input_type: text
          antlers: false
          display: 'Section 4 Title'
          type: text
          icon: text
          localizable: true
          listable: hidden
      -
        handle: short_title4
        field:
          input_type: text
          antlers: false
          display: 'Section 4 Short Title'
          type: text
          icon: text
          localizable: true
          listable: hidden
      -
        handle: content4
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: false
          display: 'Section 4 Content'
          type: markdown
          icon: markdown
          localizable: true
          listable: hidden
      -
        handle: image4
        field:
          mode: grid
          container: assets
          restrict: false
          allow_uploads: true
          max_files: 1
          display: 'Section 4 Image'
          type: assets
          icon: assets
          listable: hidden
      -
        handle: title5
        field:
          input_type: text
          antlers: false
          display: 'Section 5 Title'
          type: text
          icon: text
          localizable: true
          listable: hidden
      -
        handle: short_title5
        field:
          input_type: text
          antlers: false
          display: 'Section 5 Short Title'
          type: text
          icon: text
          localizable: true
          listable: hidden
      -
        handle: content5
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: false
          display: 'Section 5 Content'
          type: markdown
          icon: markdown
          localizable: true
          listable: hidden
      -
        handle: image5
        field:
          mode: grid
          container: assets
          restrict: false
          allow_uploads: true
          max_files: 1
          display: 'Section 5 Image'
          type: assets
          icon: assets
          listable: hidden
  quote:
    display: Quote
    fields:
      -
        handle: quote_author
        field:
          input_type: text
          antlers: false
          display: 'Quote Author'
          type: text
          icon: text
          localizable: true
          listable: hidden
      -
        handle: quote_text
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: false
          display: 'Quote Text'
          type: markdown
          icon: markdown
          localizable: true
          listable: hidden
      -
        handle: quote_image
        field:
          mode: grid
          container: assets
          restrict: false
          allow_uploads: true
          max_files: 1
          display: 'Quote Background Image'
          type: assets
          icon: assets
          listable: hidden
